### ISSUE TITLE
Τηλεδιάσκεψη

### ISSUE THREAD

**Issue by epidrome** [courses-ionio/cscw#154]
[Οδηγίες για την σύνδεση στην τηλεδιάσκεψη](https://courses-ionio.github.io/help/distance/)

κωδικός: 4qHtfW

Η τηλεδιάσκεψη θα γίνεται στις ώρες του μαθήματος, καθώς και σε συνδυασμό με την ασύγχρονη επικοινωνία στο αποθετήριο της εργασίας, έτσι ώστε να προχωρήσει το μάθημα κανονικά (ή μάλλον καλύτερα και από κανονικά ;-)

Σας παρακαλώ να γραφτείτε και σε αυτό το θέμα για να ενημερώνεστε σχετικά με τις ώρες της σύγχρονης συνάντησης

**Comment by epidrome** [comment]
Η συνάντηση σήμερα θα αρχίσει στις 8μμ

**Comment by jimDragon** [comment]
Οι τηλεδιασκέψεις θα συνεχιστούν στις διακοπές το πάσχα;

**Comment by epidrome** [comment]
ναι, **μάλλον** θα γίνει αναπλήρωση την Παρασκευή 24 Απριλίου

**Comment by epidrome** [comment]
Αύριο Παρ. 24 Απρ. θα γίνει συνάντηση στις 8μμ

**Comment by epidrome** [comment]
Σήμερα Τετ. 29 Απριλ. δεν θα γίνει η σύγχρονη συνάντηση έτσι ώστε να υπάρχει περισσότερος χρόνος για την συμμετοχή στα ασύγχρονα εργαλεία (π.χ., issues, bugs, wiki)

**Comment by provopoulos** [comment]
Έχει γίνει κάποια αλλαγή στον κωδικό για την εξ' αποστάσεως συνάντηση μέσω Zoom; Ο παρεχόμενος κωδικός (******986) δεν είναι έγκυρος.

**Comment by epidrome** [comment]
4qHtfW

έχεις δίκιο! μάλλον το ζουμ έβαλε κωδικό και για την ώρα δεν μπορώ να τον βγάλω, για προσπάθησε πάλι

**Comment by epidrome** [comment]
Σήμερα Παρ. 15 Μαϊου δεν θα γίνει η σύγχρονη συνάντηση έτσι ώστε να υπάρχει περισσότερος χρόνος για την συμμετοχή στα ασύγχρονα εργαλεία (π.χ., issues, bugs, wiki)
